name: Disable workflow
on:
  workflow_call:
    inputs:
      workflow:
        description: 'The name, ID, or file name of the workflow you want to disable'
        # default: 'default-value'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      workflow:
        description: 'The name, ID, or file name of the workflow you want to disable'
        # default: 'default-value'
        required: true
        type: string
permissions:
  actions: write

jobs:
  disable-workflow:
    name: disable workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          sparse-checkout: .github          
      - name: disable workflow
        run: gh workflow disable ${{ inputs.workflow }}
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
