name: Enable workflow
on:
  workflow_call:
    inputs:
      workflow:
        description: 'The name, ID, or file name of the workflow you want to enable'
        # default: 'default-value'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      workflow:
        description: 'The name, ID, or file name of the workflow you want to enable'
        # default: 'default-value'
        required: true
        type: string
permissions:
  actions: write

jobs:
  enable-workflow:
    name: enable workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          sparse-checkout: .github          
      - name: enable workflow
        #run: gh workflow enable ${{ inputs.workflow }}
        run: gh workflow enable ${{ inputs.workflow }}
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
